In [1]:
from __future__ import annotations

class listnode:
    def __init__(self, val: int = 0, next: listnode | None = None):
        self.val = val
        self.next = next

node_1 = listnode(10)
node_2 = listnode(20)
node_1.next = node_2
node_3 = listnode(30)
node_2.next = node_3

pointer_variable = node_1
while pointer_variable is not None:
    print(pointer_variable.val)
    pointer_variable = pointer_variable.next

10
20
30


In [5]:
import numpy as np
l = [1, 2, 3, 4, 5, 6]
print(type(l))
n_l=np.array(l)
type(n_l)

<class 'list'>


numpy.ndarray

use myenv 


In [4]:
import numpy as np
l = [1, 3, 5, 7, 9]
print(type(l))
n_1 = np.array(l)
print(n_1)

<class 'list'>
[1 3 5 7 9]


In [6]:
l = [1, 2, 3, 4, 5, 6]
print(type(l))
n_1 = np.array(l)
type(n_1)
print(f"Dimension of n_1: {n_1.ndim}")

<class 'list'>
Dimension of n_1: 1


In [7]:
a = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])
b = np.array([[1, 2], [3, 4], [4, 5]])
print(a)
print(f"dimension of a: {a.ndim}")
print(b)
print(f"dimension of b: {b.ndim}")

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
dimension of a: 2
[[1 2]
 [3 4]
 [4 5]]
dimension of b: 2


In [8]:
a = np.ones(shape=(3, 2), dtype= np.int64)
b = np.ones(shape= (3, 2), dtype=np.float64)
print(a)
print(b)


[[1 1]
 [1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
a_empty = np.empty(shape=(3, 3), dtype=np.int64)
b_empty = np.empty(shape=(2, 2), dtype=np.float64)
print(a_empty)
print(b_empty)

[[23925768161198147 32370111954616435 20548029787209820]
 [31525678432190556 27303570963497028 27866499440705628]
 [23644293187764321      481043480677 22236875352703071]]
[[2.12199579e-314 1.45356712e-311]
 [4.66397970e-321 3.79442416e-321]]


In [12]:
a = np.arange(start=0, stop=11, dtype=np.int64)
print(a)
b = np.arange(start=0, stop=11, dtype=np.float64)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
a_empty = np.empty(shape=(3, 3), dtype=np.int64)
b_empty = np.empty(shape=(2, 2), dtype=np.float64)
print(a_empty)
print()
print(b_empty)

[[25895968444448860 23925768161198147 32370111954616435]
 [20548029787209820 31525678432190556 27303570963497028]
 [27866499440705628 23644293187764321      481043480677]]

[[2.12199579e-314 1.45356712e-311]
 [4.66397970e-321 3.79442416e-321]]


In [15]:
np.set_printoptions(precision = 4)
N = 8
x1 = np.linspace(start=0, stop=0, num=N, endpoint=True)
x2 = np.linspace(start=0, stop=10,num=N, endpoint=False)
x3 = np.linspace(start=0, stop=10, num=N)
print(x1)
print(x2)
print(x3)


[0. 0. 0. 0. 0. 0. 0. 0.]
[0.   1.25 2.5  3.75 5.   6.25 7.5  8.75]
[ 0.      1.4286  2.8571  4.2857  5.7143  7.1429  8.5714 10.    ]


In [4]:
#leetcodesolution
#two sum

from typing import List
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        nums_dict = dict()
        for index, value in enumerate(nums):
            if (target - value) in nums_dict:
                return [nums_dict[target - value], index]
            nums_dict[value] = index